### ISSUE TITLE
Side effect of using VisibilityInfo.numMostlyPerpWaySegments for corner facades

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#14]
It requires fine tuning. I'll investigate it.

![image](https://user-images.githubusercontent.com/613295/119173833-752e3c80-ba70-11eb-9ca7-81d8f2ce70f3.png)

**Comment by polarkernel** [comment]
I observed, that the facet facades (blue arrows) in _manhattan_01.osm_ get correctly classified as front facades. They are not excluded due to their angles in the condition at line [50](https://github.com/prochitecture/blosm/blob/13524ad250748baf2c38926503526b463b39feef/action/facade_classification.py#L50) in facade_classification.py, because the condition `visInfo.numMostlyPerpWaySegments >= 2` is True. But their sight value _edgeSight_ is larger than the threshold _FrontFacadeSight_, so that they get classified as front facades, like all the other facades, that meet the angle condition.

However, the condition in line [72](https://github.com/prochitecture/blosm/blob/13524ad250748baf2c38926503526b463b39feef/action/facade_classification.py#L72), originally intended for this special case, is not used for these facet facades, but produces wrong classifications (red arrows) on other edges. If we remove (comment) lines [72-74](https://github.com/prochitecture/blosm/blob/13524ad250748baf2c38926503526b463b39feef/action/facade_classification.py#L72-L74) delivers correct results for all edges, in my opinion.

<img src="https://user-images.githubusercontent.com/48180714/119260158-d7eb1980-bbd1-11eb-999c-be599cb8037c.png" width="500">

I don't know, where your examples above is made from, but I assume, these wrong classifications would be correct too.

**Comment by vvoovv** [comment]
I commented the code at _action/facade_classification.py_ to treat the corner facades. Yes, it solved the problem of corner facades in _manhattan_01.osm_. It also solved the problem from the first message (_berlin_karl_marx_allee.osm_, marked on the image below along with the corner facade).

However a corner facade in _berlin_karl_marx_allee.osm_ isn't classified correctly.

![image](https://user-images.githubusercontent.com/613295/119336754-ad16c900-bc96-11eb-97ed-f14338fe63f9.png)

![image](https://user-images.githubusercontent.com/613295/119337109-1e567c00-bc97-11eb-97e1-1ef37d3026fa.png)

**Comment by polarkernel** [comment]
I refactored the classification code and tried another approach for these corner facades. The algorithm works as follows:

1. Find front facades using the first step of the current algorithm.
2. Identify unclassified facades that lie between two front facades.
3. Take the two way-segments, that are associated to these front facades.
4. Using there unit vectors, compute their dot product, which is the cosine of the angle between them.
5. If the cosine is below a threshold _CornerFacadeWayAngle_, classify the facade between the front facades as front facade.

This is still your idea of looking at the angles of the way-segments, but from another perspective. It seems to solve all issues with these corner facades we had until now. The new code is committed.

**Comment by vvoovv** [comment]
The method works perfectly. But what if there are more then one corner facades or what if the corner part has the form of an arc?

I'll close the issue till we encounter an example for that cases.
