### ISSUE TITLE
Incorrect classification in bern_old_town.osm

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#15]
![image](https://user-images.githubusercontent.com/613295/119360694-8dda6480-bcb3-11eb-8044-d9eeeb6badc3.png)

![image](https://user-images.githubusercontent.com/613295/119361340-3ab4e180-bcb4-11eb-9a9c-b8ea33afb36e.png)

**Comment by vvoovv** [comment]
Can crossing way-segments have a lower priority in comparison to the _normal_ way segments?

**Comment by polarkernel** [comment]
> Can crossing way-segments have a lower priority in comparison to the normal way segments?

Yes, this was the case for the code before the commit of today. As only one way-segment can be associated to a facade edge, the segment that made the crossing was associated. Very often, this was due to a way of low priority. But in most cases, the edge is also parallel to a street of higher priority, the result was often weird. In the current version, all crossed edges get front edges. Let's observe whether this gives more meaningful results or not. The issue in _bern\_old\_town.osm_ at least is solved.

**Comment by vvoovv** [comment]
Ok, I close the issue.
