### ISSUE TITLE
Strasse der Pariser Kommune

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#52]
The selected street sections look strange as the ones crossing at an intersection. Would it be more appropriate here to have a long area that connects the two way-clusters (at the bottom and at the top) with different widths?

![image](https://user-images.githubusercontent.com/613295/224817730-b2df8b61-b485-4fb4-b390-73b957fcfdb2.png)

**Comment by polarkernel** [comment]
> Would it be more appropriate here to have a long area that connects the two way-clusters (at the bottom and at the top) with different widths?

This is difficult to implement, because the two areas are created in two separate processes. The upper area is a clipped cluster end and is processed in `createClusterIntersections()`, while the lower area is a common way-intersection that is processed at the end in `createOutput()`.

Clipping a cluster is a tricky process, applied for cluster-ways, that suddenly change their detected way-distance. Without that, the cluster would be skipped and would look like [this](https://github.com/prochitecture/blosm/issues/44#issuecomment-1368087367). This process measures the distance between the ways as long as it is almost constant. At the position, where a distance change is detected, the cluster is clipped, and a cluster end is constructed. 

Maybe a final "cleaning" of the whole scene could be realized, that joins nearby intersection areas

**Comment by vvoovv** [comment]
Let's keep it as is.

Instead I suggest to discuss how to detect if sidewalks are not needed for a street section. I created #53 for that.
