### ISSUE TITLE
A problem with the latest commit ac83cf2

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#55]
```
manager.intersectionAreas[16].clusterConns: {18: 5}
```
But actually it should be `{18: 4}` since the connector start with the vertex with the index _4_.

```
manager.wayClusters[18].endConnected: False
```

But it actually both ends of `manager.wayClusters[18]` are connected to intersections.

**Comment by polarkernel** [comment]
In which scene did this problem occur?

**Comment by vvoovv** [comment]
berlin_karl_marx_allee.osm

**Comment by vvoovv** [comment]
Also way/overlap_handler.py contains the uncommented line:
```python
from debugPlot import *
```

**Comment by polarkernel** [comment]
> But actually it should be `{18: 4}` since the connector start with the vertex with the index _4_.

The way `manager.waySectionLines[48]` is not exactly perpendicular to the cluster, so the connector is slightly tilted and makes two vertices 3 and 4. So the start index `{18: 5}` is correct, the cluster connects between vertices 5 and 6:

<img src="https://user-images.githubusercontent.com/48180714/228242372-e382894a-ac1a-4ee5-aa55-9596fc1cbcce.png" width="400">

> `manager.wayClusters[18].endConnected: False`
But it actually both ends of `manager.wayClusters[18]` are connected to intersections.

Fixed. The new cluster ends of the overlap handler didn't distinguish start and end.

> Also way/overlap_handler.py contains the uncommented line:
`from debugPlot import *`

Fixed. The automatic commit by my development environment has caused me a lot of confusion, sorry.

I also fixed another bug that was found since the last commit. However, this did not affect the known scenes that already work.

**Comment by vvoovv** [comment]
> The way `manager.waySectionLines[48]` is not exactly perpendicular to the cluster, so the connector is slightly tilted and makes two vertices 3 and 4.

Sorry, I didn't notice that.

> Fixed. The new cluster ends of the overlap handler didn't distinguish start and end.

Thanks.
