### ISSUE TITLE
Self-intersections in intersection polygons

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#58]
berlin-karl-marx-allee.osm

All intersection polygons here have self-intersections:
![image](https://user-images.githubusercontent.com/613295/233269132-3ddcf260-8bfe-4c31-ad2d-9f95f6a8f98a.png)

manager.intersectionAreas[28]
![image](https://user-images.githubusercontent.com/613295/233269841-b5034091-da39-4c53-8188-b47964d0ba0b.png)

manager.intersectionAreas[29]
![image](https://user-images.githubusercontent.com/613295/233269973-6adec00a-fa6a-4bd4-9c7b-7a5219b7a573.png)

manager.intersectionAreas[30]
![image](https://user-images.githubusercontent.com/613295/233270173-7eaefd94-0811-4244-8bf1-a82b09973399.png)

manager.intersectionAreas[31]
![image](https://user-images.githubusercontent.com/613295/233270412-e960f44f-6cc8-4b4a-a779-e31d0ddc17a2.png)

**Comment by polarkernel** [comment]
> All intersection polygons here have self-intersections:

Fixed in last commit. As usually, some floating point issues.

Part of this fix is a piece of new code I've been preparing for some time. Unfortunately, even after more than a dozen new ideas and attempts, I have not been able to solve the overlapping ways problem since months. So, the patch of today will not remain as final solution.

**Comment by vvoovv** [comment]
Thank you!
