### ISSUE TITLE
A problem on the roundabout

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#64]
_facade_visibility/karl_marx_allee.osm_

There is probably a problem with the width and offset of the roadway on one of the intersections of the roundabout.

![image](https://github.com/prochitecture/blosm/assets/613295/19d6ef70-9a9f-40da-be78-eeb7af612c35)

![image](https://github.com/prochitecture/blosm/assets/613295/2d0f5d3e-7d43-4ec9-ad6c-6eb98e8c8145)

**Comment by polarkernel** [comment]
> There is probably a problem with the width and offset of the roadway on one of the intersections of the roundabout.

Isn't this an issue in osm-tagging? The three successive ways leaving the roundabout are tagged as follows:

way [932638439](https://www.openstreetmap.org/way/932638439): oneway=yes, lanes=3
way [284760972](https://www.openstreetmap.org/way/284760972): oneway=yes, lanes=2, turn:lanes=none|merge_to_left
way [284761029](https://www.openstreetmap.org/way/284761029): oneway=yes, lanes=1

So there is a jump from 3 to 2 lanes between the first two ways, without any turn-lane tag. It triggers erroneously my algorithm to build a (wrong) `TransitionSideLane`. The second pair of ways is then a correct `TransitionSideLane`, but now missed, because one of the ways is already used.

<img src="https://github.com/prochitecture/blosm/assets/48180714/91bdc797-d4ff-4565-88ad-0458b0c05125" width="300">

I will try to handle such cases.

**Comment by polarkernel** [comment]
Mea culpa, sometimes one should stand back a bit. The first transition is just a `TransitionSymLane`, which makes the way smaller, while the second could be the `TransitionSideLane`, but doesn't, because there is an intersection there. There was a bug in the detection algorithm, which is corrected now. The solution is committed.

**Comment by vvoovv** [comment]
Thanks!
