### ISSUE TITLE
The centerline does not touch the intersetion

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#68]
`streets/nabrezie.osm`

The centerline does not touch the intersection at the middle of the area.

![image](https://github.com/prochitecture/blosm/assets/613295/6a0dc3d9-ae7b-428f-a81f-f0a7ae4e27e1)

![image](https://github.com/prochitecture/blosm/assets/613295/c53cef8b-8c1a-4bfd-8c9a-75b71f447925)

**Comment by vvoovv** [comment]
Also in _streets/versmannstrasse.osm_

![image](https://github.com/prochitecture/blosm/assets/613295/e1b95a3d-2cb8-41cc-90fe-9fc063ea546f)

**Comment by polarkernel** [comment]
> The centerline does not touch the intersection at the middle of the area.

This was a strange bug, and I want to report it in more detail because the problem may be interesting later. As usual, it's a problem of computational geometry, and I wonder why we didn't observe it already a long time ago.

The computation of intersections is based on the intersection points of the boundaries of the way-sections. Let us assume that we have two centerlines (red and green solid lines) of two way-sections and, at a given distance, their borders (dotted lines). The boundaries intersect at the black point. To get the trim position of the blue centerline, the closest point to the intersection point is calculated, which is located on the line perpendicular to the blue way (black cross). The blue path must be trimmed at this position.

<img src="https://github.com/prochitecture/blosm/assets/48180714/46f5dff9-00a8-4270-8c45-7c179e9dc202" width="400">

But there may be situations where the nearest point can't be on a perpendicular line, as shown in the next image. The method `orthoProj` of the class _PolyLine_ returns the end of the edge as the nearest point (black cross). To be correct, an additional point (green dot) must be added to the intersection area, using a back projection to the boundary of the blue way-section. This fixes the bug and provides a useful trim value for the path segment:

<img src="https://github.com/prochitecture/blosm/assets/48180714/6db393c0-e8fa-446d-9f91-b06301f0c95c" width="400">

The fixed code is committed.

**Comment by vvoovv** [comment]
Thanks.
