### ISSUE TITLE
Inconsistent data in an instance of Street

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#86]
facade_visibility/berlin_karl_marx_allee.osm
Street.ID = 1016

![image](https://github.com/prochitecture/blosm/assets/613295/2b87676a-868e-4fd6-8f03-c7fb995ac512)

**Comment by polarkernel** [comment]
Everything is OK, it's a `Street` with a `SideLane` in the linked list:

<img src="https://github.com/prochitecture/blosm/assets/48180714/a47b9f74-ddc2-4a42-babd-cfbeff38af71" width="500">

```python
street.tail = Section s2
street.head = Section s1
street.tail.succ = s2.succ = None
street.tail.pred = SideLane sl2
```
Please use lower case letters for `id`, `Street.ID` is the class variable, that counts the sum of instances of the class.

**Comment by vvoovv** [comment]
Maybe I misunderstood it. I thought it's like in the train. The tail is at the end of the train and the head is at the beginning, so the train driver is in the head of the train.

**Comment by polarkernel** [comment]
> Maybe I misunderstood it. I thought it's like in the train. The tail is at the end of the train and the head is at the beginning, so the train driver is in the head of the train.

As far as I understand it, it is the same with trains. When the driver is at the head of the train, the cars behind him (its successors) are linked as a single linked list, while the last one has no successor. New cars are added at the end (the tail) of the train. Since finding the end of a linked list requires traversing the entire list, which is not the case for a train, the tail is used to find the end more quickly. Predecessor links enable moving in both directions in the list, which is not required with a train. Almost all implementations of doubly-linked lists, that I know of, use this notation.
