### ISSUE TITLE
Additional data for the street renderer

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#87]
The following additional data are needed for the street renderer.

(1)
Each street item should have a reference to its `street`, for example, `item.street`

(2)
It would be good to have a list of side lane transitions, for example, `manager.sideLanes` or `manager.sideLaneTransitions`.

I can add those data in the street renderer. But I thought it would be easier to add them in the street generator during the initialization.

**Comment by polarkernel** [comment]
> The following additional data are needed for the street renderer.

Committed.

> Each street item should have a reference to its `street`, for example, `item.street`

For now, `street` is an attribute of `Item`. However, this is not a proper solution, because for example `Intersection` or `Street` also get this attribute, which does not make sense for these items.

> It would be good to have a list of side lane transitions, for example, `manager.sideLanes` or `manager.sideLaneTransitions`.

The Python lists `manager.transitionSideLanes` and `manager.transitionSymLanes` are now populated with values.
