### ISSUE TITLE
Nondeterministic results of the facade classification

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#9]
Got different results for the same command line parameters. Also note the edge marked with the magenta color. It isn't classified as the front facade.

![image](https://user-images.githubusercontent.com/613295/117217169-a4ef0a80-ae09-11eb-83d7-7e0040dd5a42.png)

![image](https://user-images.githubusercontent.com/613295/117217283-ce0f9b00-ae09-11eb-8233-ff8fa95c460a.png)

**Comment by vvoovv** [comment]
Edges of the upper buildings facing the street are classified as the front ones in one attempt and the side ones in another attempt.

**Comment by polarkernel** [comment]
> Edges of the upper buildings facing the street are classified as the front ones in one attempt and the side ones in another attempt.

????? Very magic! What was the OSM data file?

**Comment by vvoovv** [comment]
> ????? Very magic! What was the OSM data file?

manhattan_01.osm

![image](https://user-images.githubusercontent.com/613295/117273196-92ee8580-ae64-11eb-868b-e10e4b926f3f.png)

**Comment by vvoovv** [comment]
Can you reproduce that result?

**Comment by polarkernel** [comment]
> Can you reproduce that result?

At least I get always the same wrong result, as in the bottom image of your examples. I also know that this issue comes from replacing the way-segment in the function _VisibilityInfo.\_\_gt\_\_()_. No solution yet, I will treat it with the other tests forseen in this function.

**Comment by vvoovv** [comment]
The problem is still there:

(karl_marx_allee.osm)

![image](https://user-images.githubusercontent.com/613295/118856664-dd99e400-b8df-11eb-9669-a4afe9a581f5.png)

![image](https://user-images.githubusercontent.com/613295/118856691-e5f21f00-b8df-11eb-8754-5783c8df6aea.png)

**Comment by polarkernel** [comment]
> The problem is still there:

This time I was able to reproduce your result. The wrong classification appeared once among five runs using the 64-bit interpreter and two times among five with the 32-bit interpreter. I know such issues fromm C++, when a misused pointer is reading data from uninitialized memory, but a far as I understand Python, this should not be able to happen. It is difficult to get hints from the net, as there almost all results refer to AI applications, where random generators are involved. But as far as I know, we do not have random values in our code.

**Comment by vvoovv** [comment]
There is a question [Why is dictionary ordering non-deterministic?](https://stackoverflow.com/questions/14956313/why-is-dictionary-ordering-non-deterministic). But then in the reply:
`From Python 3.7, this order-preserving behaviour is guaranteed`

**Comment by vvoovv** [comment]
It might be also related to multithreaded operations at numpy.

**Comment by vvoovv** [comment]
More mistery. The same winning way segment, the same visibility, But different results for the building edge. Sorry for the yellow color.

![image](https://user-images.githubusercontent.com/613295/118971728-711ef380-b978-11eb-864c-bceac356257f.png)

![image](https://user-images.githubusercontent.com/613295/118971775-7b40f200-b978-11eb-8a47-58f8e387524b.png)

**Comment by vvoovv** [comment]
> More mistery.

If you want to find that building edge during the debugging:
File: berlin_karl_marx_allee.osm
edge.v1[0]==117.37134892782458
edge.v1[1]==1.9161035727416749
edge.v2[0]==132.88107678992375
edge.v2[1]==93.96658735699803

**Comment by vvoovv** [comment]
I found that _avgDist_ takes different values each time.

**Comment by vvoovv** [comment]
I didn't dig it in further.
My suspicion is that _scipy.spatial.KDTree_ provides different output each time.

**Comment by polarkernel** [comment]
> I found that avgDist takes different values each time.

Just found the same difference.

> I didn't dig it in further.
My suspicion is that scipy.spatial.KDTree provides different output each time.

You may be right. I will get in depth tomorrow, can't continue today.

**Comment by polarkernel** [comment]
>  found that avgDist takes different values each time.

Got the bug! The computation of the weighted average distance was made at the end of every loop for a way-segment. But at this time, it was not yet clear, wheter the current way-segment will win. Therefore, this computation had to be shifted to the very end of the visibility computation, where for every edge the winning way-segment is crowned. Then, the result of the classification gets correct and stable. The new version is committed. Probably your skills for optimizations is requested.

However, this would only explain, why the result was wrong, but not the non-determinism. Digging for this issue, I found that either the order of the ways in the loop at line [109](https://github.com/prochitecture/blosm/blob/06d771d1db51789f27b7025cbf8a5817e90042a2/action/facade_visibility.py#L108) or of the way-segments in the loop at line [110](https://github.com/prochitecture/blosm/blob/06d771d1db51789f27b7025cbf8a5817e90042a2/action/facade_visibility.py#L110) is non-deterministic. This produced the bug mentioned above, but every time in a different way because of the different order. I don't know, where this non-determinism comes from, but didn't invest a lot of time to find that.

**Comment by vvoovv** [comment]
> Got the bug! 

Thank you!

> However, this would only explain, why the result was wrong, but not the non-determinism. 

I found the reason for the non-determinism. Way categories were defined in _defs.way_ as Python sets. Iteration through the elements of a Python set isn't deterministic. I replaced Python sets with Python lists.
