### ISSUE TITLE
Sections don't fit each other after applying the offset

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#98]
There is a shift about 1cm between the sections after applying the offset.

![image](https://github.com/prochitecture/blosm/assets/613295/91c75c41-e0b4-463f-91cc-15ab5b1d4a50)

The same in Blender after some transformations:
![image](https://github.com/prochitecture/blosm/assets/613295/6eb936c3-ffa3-49b4-9fb8-26d435d02c3e)

_____

![image](https://github.com/prochitecture/blosm/assets/613295/ab4855d7-7054-4a7b-aee2-607b7f173df3)

![image](https://github.com/prochitecture/blosm/assets/613295/2c49220f-67da-4ae7-802a-1072406d92a2)

**Comment by polarkernel** [comment]
> There is a shift about 1cm between the sections after applying the offset.

This effect comes from the width ratio correction discussed [here](https://github.com/prochitecture/blosm/issues/57#issuecomment-1544025403). Let me explain using your upper example with the section id's 115 and 126, the second example has exactly the same dimensions.

The sections have the following attributes:

Section 126 (incoming): 
```python
totalLanes: 3
width: 8.1
laneWidth: 2.7
```
Section 115 (outgoing):
```python
totalLanes: 4
width: 10.8
laneWidth: 2.7
```
The width ratio correction becomes:
```python
pixels_for_126 =  3 * 220 + 8 * 2 = 676
pixels_for_115 =  4 * 220 + 8 * 3 = 904
ratio = 904 / 676 = 1.337278
```
To complete the width ratio correction recipe, the width and lane width of the wider section are corrected to:
```python
new_width = ratio * width = 10.83195
new_laneWidth = new_width / totalLanes = 2.707988
```
These values are used to calculate the required offset of the wider section. Since there is an additional lane, the offset is half this line width and negative because it is a left turn:
```python
offset = new_laneWidth / 2.  * -1 = -1.353994
```
The widths to the left and right of the centerline for section 115 will now be:
```python
leftWidth = width/2 - offset = 6.76997
rightWidth = width/2 + offset = 4.061982
```
For the smaller section 126, the widths on either side of the centerline are equal:
```python
leftWidth = rightWidth = width/2 = 4.05
```
Now we see a difference between the right width of section 115 and the right width of section 126. This corresponds to the difference you have measured in your examples:
```python
rightWidth _115 - rightWidth_126 = 0.0119822
```

The problem occurs when calculating the left and right widths of section 115. Both, `width` and `offset` are based on corrected values. By the time the left and right widths are calculated, the original widths are no longer available. I could solve this with two different solutions:

1. Modify `offset`, so that the computation of the left and right widths gives results that fit to the incoming section. To do this, I need to know, how exactly you use `offset`.
2. Store the old, uncorrected widths in `Section`, so that they can be used for the computation of the left and right widths.

In any case, we must be aware that the widths of the outgoing section are corrected and do not meet the lane widths of the incoming section. What is your opinion?

**Comment by vvoovv** [comment]
![image](https://github.com/prochitecture/blosm/assets/613295/d949871f-3c4d-4f8f-adc7-f96643f5ba68)

The red line on the image above is the centerline of the original OSM-way and the centerline of the street section on the right.

`WidthL` is the width of the section on the left.
`WidthR` is the width of the section on the right.

A profile is applied to the centerline of a street section to generate a roadway. That's why an offset is required if a street section is not symmetrical relative to the original OSM-way.

It's easy to see from the above image that the absolute value of the offset should be calculated as:
`0.5*(WidthL-WidthR)`

In our case:
`WidthL = 10.83195` (`id:115`, the modified width)
`WidthR = 8.1` (`id:126`)
`offset = 0.5 * (10.83195 - 8.1) = 1.365975`

Currently, the absolute value of the offset is equal to `1.35399`.
`1.365975 - 1.35399 = 0.011985`

**Comment by polarkernel** [comment]
> It's easy to see from the above image that the absolute value of the offset should be calculated as:
`0.5*(WidthL-WidthR)`

Of course! It's funny how you can sometimes get lost when you focus on one solution, while there's actually a much simpler way. I always tried to solve it using the lanes.

I fixed the code and committed the correct solution.

**Comment by vvoovv** [comment]
Thanks. They fit now perfectly.
